export const errors = {

    TVM_DESERIALIZATION_ERROR: 9,

    ERR_INVALID_FLAG_VALUE: 100,
    ERR_PRUNED_NO_LEVEL_1: 101,
    ERR_INVALID_SENDER: 102,
    ERR_MERKLE_PRUNE_HASH: 103,
    ERR_NEW_KEYBLK_PRUNED: 104,
    ERR_TX_PROOF_PRUNED: 105,
    ERR_BURROWING_INTO_TX: 106,

    ERR_BLOCK_TD_ID: 200,
    ERR_BLKINFO_TD_ID: 201,
    ERR_BLK_NOT_MASTER: 202,
    ERR_BLK_NOT_KEYBLK: 203,
    ERR_BLKEXTRA_TD_ID: 204,
    ERR_NO_MCBLKEXTRA: 205,
    ERR_MCBLKEX_TD_ID: 206,
    ERR_MCBE_NOT_KEYBL: 207,
    ERR_CP34_NOT_FOUND: 208,

    ERR_BAD_VSET_TYPE: 300,
    ERR_MAIN_GT_TOTAL: 301,
    ERR_MAIN_IS_ZERO: 302,
    ERR_VSET_DICT_HOLE: 303,
    ERR_BAD_VAL_TYPE: 304,
    ERR_PUBKEY_TD_ID: 304,

    ERR_BAD_GLOBAL_ID: 400,
    ERR_BAD_SEQNO: 401,
    ERR_BAD_GEN_TIME: 402,
    ERR_BAD_LT: 403,
    ERR_PREV_KEY_SEQNO: 404,

    ERR_NOT_READY: 500,
    ERR_INVALID_SIGNATURE: 501,
    ERR_NOT_ENOUGH_WEIGHT: 502,
    ERR_INVALID_SIGNER: 503,
    ERR_BLK_INFO_PRUNED: 504,
    ERR_UNEXPECTED_EXOTIC: 505,
    ERR_INVALID_BLKID_HDR: 506,
    ERR_INVALID_ROOT_HASH: 507,
    ERR_INVALID_BLKID_STR: 508,

    ERR_MISSING_BLOCK: 600,
    ERR_MISSING_SIGNATURES: 601,
    ERR_INCORRECT_BLOCK: 602,
    ERR_NO_LITE_CLIENT_SUPP: 603,

    ERR_TX_HASH_INVALID: 630,

    ERR_MISSING_SHARD_PROOF: 700,
    ERR_NO_SHARD_PROOF_LINK: 701,
    ERR_EXTRA_SHARD_PROOF: 702,
    ERR_EXTRA_SHARD_HINTS: 703,
    ERR_DEVIANT_SHARD_PROOF: 704,

    ERR_SHARD_PROOF_BT_FORK: 710,
    ERR_SHARD_PROOF_DSC_HDR: 711,
    ERR_SHARD_PROOF_BAD_HASH: 712,
    
}

let errorMap: Record<number, string> = Object.fromEntries(Object.entries(errors).map(([key, value]) => [value, key]));

export function describeError(code: number): string {
    if (code < 32) {
        return `TVM error ${code}`;
    }
    return errorMap[code] || `Unknown user error code ${code}`;
}